language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - nickatgit@yandex.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - rm -rf .cache
  - rm -rf public
  - npm run build
deploy:
  provider: pages
  skip-cleanup: false
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: develop
